"""update migration

Revision ID: 0e4924a1a489
Revises: 1e338068d0f3
Create Date: 2017-05-08 16:58:33.324995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4924a1a489'
down_revision = '1e338068d0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=64), nullable=True),
    sa.Column('itemId', sa.String(length=120), nullable=True),
    sa.Column('time', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('extra', sa.String(length=120), nullable=True),
    sa.Column('addr', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_addr'), 'record', ['addr'], unique=True)
    op.create_index(op.f('ix_record_extra'), 'record', ['extra'], unique=True)
    op.create_index(op.f('ix_record_itemId'), 'record', ['itemId'], unique=True)
    op.create_index(op.f('ix_record_time'), 'record', ['time'], unique=True)
    op.create_index(op.f('ix_record_type'), 'record', ['type'], unique=True)
    op.create_index(op.f('ix_record_userId'), 'record', ['userId'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_userId'), table_name='record')
    op.drop_index(op.f('ix_record_type'), table_name='record')
    op.drop_index(op.f('ix_record_time'), table_name='record')
    op.drop_index(op.f('ix_record_itemId'), table_name='record')
    op.drop_index(op.f('ix_record_extra'), table_name='record')
    op.drop_index(op.f('ix_record_addr'), table_name='record')
    op.drop_table('record')
    # ### end Alembic commands ###
