"""update migration

Revision ID: 1e338068d0f3
Revises: 3d41282cc4a4
Create Date: 2017-05-08 16:49:33.097753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e338068d0f3'
down_revision = '3d41282cc4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('size', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_itemname'), 'item', ['itemname'], unique=True)
    op.create_index(op.f('ix_item_size'), 'item', ['size'], unique=True)
    op.create_index(op.f('ix_item_type'), 'item', ['type'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_type'), table_name='item')
    op.drop_index(op.f('ix_item_size'), table_name='item')
    op.drop_index(op.f('ix_item_itemname'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
